#!/usr/bin/env bash

set -euo pipefail

if [[ "$#" -ne 0 ]]; then
  echo "${0##*/}: Expected no arguments" >&2
  exit 2
fi

# chezmoi external files stuff should get this file,
# which is a script that should have one function: kitty_keys
source "${HOME}/.bin/other/kitty_keys.sh"
kitty_keys
