#!/usr/bin/env bash

set -euo pipefail

if [[ "$#" -ne 0 ]]; then
  echo "${0##*/}: Expected no arguments" >&2
  exit 2
fi

echo 'LC_ALL=en_US.UTF-8' | sudo tee --append '/etc/environment'
echo 'en_US.UTF-8 UTF-8' | sudo tee --append '/etc/locale.gen'
echo 'LANG=en_US.UTF-8' | sudo tee --append '/etc/locale.conf'
sudo locale-gen 'en_US.UTF-8'
